export const LOADING_DATA_START = "LOADING_DATA_START";
export const LOADING_DATA_STOP = "LOADING_DATA_STOP";
export const GET_PROVIDERS_LIST = "GET_PROVIDERS_LIST";
export const GET_FILTER_PROVIDER_DATA = "GET_FILTER_PROVIDER_DATA";
export const RESET_FILTER = "RESET_FILTER";